#!/usr/bin/env python3
"""drift — does the recorded setup still describe the real machine?

memory/araclar.md drifted for six days without anyone noticing: it claimed
four MCP servers while fourteen were connected, listed three plugins that
had been removed, and declined a tool that was live at the account layer.
Nothing was wrong with the file when written; nothing re-read it after.

One check, and it compares real state against real state — never prose.

  Counts and name sets against the previous run, stored in
  memory/_index/inventory.json. Anything added or removed is reported, which
  is the signal that the hand-written record may need a pass.

An earlier version also scanned araclar.md for backticked names that matched
nothing installed. It found the three real orphans, then produced a new class
of false positive on every fix — account-layer bundles that are real but not
local, an embedding model name, a protocol method name. A checker that cries
wolf gets ignored, so it was removed rather than patched further. `--emit`
covers the same ground honestly: the derivable facts are generated, so they
cannot drift, and only judgement is left for a human to keep true.

Exit status is always 0 — this reports, it never gates.

    python3 tools/drift.py [--json]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent   # tools/ -> rota/ -> agents
CLAUDE = Path.home() / ".claude"
ARACLAR = ROOT / "memory" / "araclar.md"
STATE = ROOT / "memory" / "_index" / "inventory.json"
EMIT = ROOT / "memory" / "_generated" / "inventory.md"



def inventory() -> dict:
    """What is actually installed, right now."""
    def names(p: Path, pat: str = "*") -> list[str]:
        return sorted(x.stem if x.is_file() else x.name for x in p.glob(pat)) if p.is_dir() else []

    mcp: list[str] = []
    cfg = Path.home() / ".claude.json"
    if cfg.exists():
        try:
            mcp = sorted((json.loads(cfg.read_text(encoding="utf-8")).get("mcpServers") or {}))
        except (json.JSONDecodeError, OSError):
            mcp = []

    plugins: list[str] = []
    pf = CLAUDE / "plugins" / "installed_plugins.json"
    if pf.exists():
        try:
            plugins = sorted((json.loads(pf.read_text(encoding="utf-8")).get("plugins") or {}))
        except (json.JSONDecodeError, OSError):
            plugins = []

    enabled: list[str] = []
    sf = CLAUDE / "settings.json"
    if sf.exists():
        try:
            s = json.loads(sf.read_text(encoding="utf-8"))
            enabled = sorted(k for k, v in (s.get("enabledPlugins") or {}).items() if v)
        except (json.JSONDecodeError, OSError):
            enabled = []

    # Servers the client last recorded as needing OAuth. This is a CACHE with
    # expiring entries, not a census: it held 13 names at the start of one
    # session and 2 by the end, without anything being authorised. Report it
    # as what it is, never as "the unauthorised servers".
    unauth: list[str] = []
    af = CLAUDE / "mcp-needs-auth-cache.json"
    if af.exists():
        try:
            unauth = sorted(json.loads(af.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError):
            unauth = []

    return {
        "skills": names(CLAUDE / "skills"),
        "agents": names(CLAUDE / "agents", "*.md"),
        "mcp": mcp,
        "plugins": plugins,
        "enabled_plugins": enabled,
        "unauthorised": unauth,
    }


def emit(inv: dict) -> None:
    """Write the derivable half of the record as a generated file.

    araclar.md drifted because it stated counts by hand. Counts are derived,
    so they should never be typed: this file is regenerated every weekly run
    and araclar.md keeps only the judgement — why a thing is here, what was
    declined and on what grounds — which no script can produce.
    """
    from datetime import date
    lines = [
        "<!-- GENERATED by rota/tools/drift.py — do not edit. -->",
        "<!-- Judgement belongs in memory/araclar.md; counts belong here. -->",
        "",
        f"# Installed inventory — regenerated {date.today().isoformat()}",
        "",
        "| what | count |",
        "|---|---|",
    ]
    label = {"skills": "Local skills", "agents": "Local agents", "mcp": "MCP servers",
             "plugins": "Plugins installed", "enabled_plugins": "Plugins enabled",
             "unauthorised": "Recorded as needing auth (cache)"}
    for k, v in inv.items():
        lines.append(f"| {label.get(k, k)} | {len(v)} |")
    for k in ("mcp", "plugins", "enabled_plugins", "unauthorised"):
        lines += ["", f"## {label[k]}", "", ", ".join(f"`{n}`" for n in inv[k]) or "(none)"]
    lines += ["", "> The auth line reads a client cache whose entries expire. Absence "
              "from it does not mean a server was authorised — only that the client "
              "has not recorded a challenge lately."]
    disabled = sorted(set(inv["plugins"]) - set(inv["enabled_plugins"]))
    if disabled:
        lines += ["", "## Installed but not enabled — earning nothing", "",
                  ", ".join(f"`{n}`" for n in disabled)]
    EMIT.parent.mkdir(parents=True, exist_ok=True)
    EMIT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    inv = inventory()
    prev = {}
    if STATE.exists():
        try:
            prev = json.loads(STATE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            prev = {}

    changes = {}
    for k, now in inv.items():
        was = prev.get(k)
        if was is None:
            continue
        added, removed = sorted(set(now) - set(was)), sorted(set(was) - set(now))
        if added or removed:
            changes[k] = {"added": added, "removed": removed}

    if "--json" in sys.argv:
        print(json.dumps({"inventory": inv, "changes": changes},
                         indent=2, ensure_ascii=False))
    else:
        counts = " · ".join(f"{k}:{len(v)}" for k, v in inv.items())
        print(f"installed  {counts}")
        if not prev:
            print("baseline   first run — nothing to compare against yet")
        elif not changes:
            print("changes    none since last run")
        else:
            for k, d in changes.items():
                for n in d["added"]:
                    print(f"  + {k}: {n}")
                for n in d["removed"]:
                    print(f"  - {k}: {n}")
        if changes:
            print("\n→ the install moved; memory/araclar.md may no longer describe it."
                  "\n  Draft a correction into memory/_inbox/, never edit it directly.")

    if "--emit" in sys.argv:
        emit(inv)
        print(f"wrote {EMIT.relative_to(ROOT)}")

    STATE.parent.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(inv, indent=2, ensure_ascii=False), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
